#!/usr/bin/env sh

sesh () {
    while IFS= read -r line; do
        case "$line" in
            "[DIR]:  "*)
                echo "THERE"
                dir="${line#"[DIR]:  "}"  # Strip "[DIR]:  "
                seshName="sesh-$(basename "$dir")"
                cd "$dir"
                tmux attach-session -t "$seshName" || echo "Creating new session $seshName ..." && tmux new-session -s "$seshName"
                ;;
            "[EXIT]"*) return ;;
            *) echo "$line" ;;
        esac
    done < <(seshCore "$@")
}
